/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.plc4x.java.direct.readwrite.model.io;

import org.apache.plc4x.java.direct.readwrite.model.DirectPacket;
import org.apache.plc4x.java.spi.generation.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

// Code generated by code-generation. DO NOT EDIT.

public class DirectPacketIO implements MessageIO<DirectPacket, DirectPacket> {

    private static final Logger LOGGER = LoggerFactory.getLogger(DirectPacketIO.class);

    @Override
    public DirectPacket parse(ReadBuffer readBuffer, Object... args) throws ParseException {
        return DirectPacketIO.staticParse(readBuffer);
    }

    @Override
    public void serialize(WriteBuffer writeBuffer, DirectPacket value, Object... args) throws ParseException {
        DirectPacketIO.staticSerialize(writeBuffer, value);
    }

    public static DirectPacket staticParse(ReadBuffer readBuffer) throws ParseException {
        readBuffer.pullContext("DirectPacket");
        int startPos = readBuffer.getPos();
        int curPos;

        long totalBytes = ((ReadBufferByteBased) readBuffer).getTotalBytes();
        // Simple Field (content)
String content = readBuffer.readString("content",  (int) (totalBytes*8), "UTF-8") ;
        readBuffer.closeContext("DirectPacket");
        // Create the instance
        return new DirectPacket(content);
    }

    public static void staticSerialize(WriteBuffer writeBuffer, DirectPacket _value) throws ParseException {
        int startPos = writeBuffer.getPos();
        writeBuffer.pushContext("DirectPacket");

        // Simple Field (content)
        String content = (String) _value.getContent();
        writeBuffer.writeString("content", (8) * (_value.getContent().length()), "UTF-8", (String) (content));
        writeBuffer.popContext("DirectPacket");
    }

}
